# Generated by Django 6.0.2 on 2026-02-24 04:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='单词')),
                ('pronunciation', models.CharField(blank=True, max_length=100, verbose_name='音标')),
                ('definition', models.TextField(verbose_name='中文释义')),
                ('example', models.TextField(blank=True, verbose_name='例句')),
                ('example_translation', models.TextField(blank=True, verbose_name='例句翻译')),
                ('unit', models.CharField(default='Unit 1', max_length=50, verbose_name='单元')),
                ('textbook', models.CharField(default='课本词汇', max_length=50, verbose_name='教材')),
                ('is_core', models.BooleanField(default=True, verbose_name='课标核心词')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20, verbose_name='班级')),
                ('title', models.CharField(max_length=100, verbose_name='作业标题')),
                ('due_date', models.DateField(verbose_name='截止日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='进行中')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_created', to=settings.AUTH_USER_MODEL)),
                ('words', models.ManyToManyField(to='words.word', verbose_name='单词列表')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='教师')),
                ('student_id', models.CharField(blank=True, max_length=20, verbose_name='学号')),
                ('class_name', models.CharField(blank=True, max_length=20, verbose_name='班级')),
                ('real_name', models.CharField(blank=True, max_length=50, verbose_name='姓名')),
                ('daily_goal', models.IntegerField(default=10, verbose_name='每日目标')),
                ('current_streak', models.IntegerField(default=0, verbose_name='连续天数')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('words_learned', models.IntegerField(default=0)),
                ('words_reviewed', models.IntegerField(default=0)),
                ('homework_done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_words', models.IntegerField(default=0, verbose_name='完成数量')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('homework', 'student')},
            },
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', '新学'), ('familiar', '熟悉'), ('mastered', '掌握')], default='new', max_length=20, verbose_name='状态')),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now, verbose_name='下次复习')),
                ('correct_count', models.IntegerField(default=0, verbose_name='正确次数')),
                ('wrong_count', models.IntegerField(default=0, verbose_name='错误次数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.word')),
            ],
            options={
                'unique_together': {('user', 'word')},
            },
        ),
    ]
