# Generated by Django 6.0.2 on 2026-02-26 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userword',
            name='ease_factor',
            field=models.FloatField(default=2.5, verbose_name='简易度系数'),
        ),
        migrations.AddField(
            model_name='userword',
            name='interval',
            field=models.IntegerField(default=1, verbose_name='间隔天数'),
        ),
        migrations.AddField(
            model_name='userword',
            name='is_learned',
            field=models.BooleanField(default=False, verbose_name='是否已学'),
        ),
        migrations.AddField(
            model_name='userword',
            name='last_reviewed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次复习'),
        ),
        migrations.AddField(
            model_name='userword',
            name='repetitions',
            field=models.IntegerField(default=0, verbose_name='连续成功次数'),
        ),
        migrations.AddField(
            model_name='userword',
            name='total_reviews',
            field=models.IntegerField(default=0, verbose_name='总复习次数'),
        ),
        migrations.AddField(
            model_name='word',
            name='category',
            field=models.CharField(blank=True, help_text='例如：CET-4、雅思、课本', max_length=50, verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='word',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], default=3, verbose_name='难度等级'),
        ),
    ]
