# Generated by Django 6.0.2 on 2026-03-07 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_userword_ease_factor_userword_interval_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='验证码')),
                ('class_name', models.CharField(max_length=20, verbose_name='目标班级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('is_used', models.BooleanField(default=False, verbose_name='已使用')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('max_uses', models.IntegerField(default=1, verbose_name='最大使用次数')),
                ('used_count', models.IntegerField(default=0, verbose_name='已使用次数')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='生成教师')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_codes', to=settings.AUTH_USER_MODEL, verbose_name='使用学生')),
            ],
            options={
                'verbose_name': '注册验证码',
                'verbose_name_plural': '注册验证码管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
